name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: python-version: "3.12"

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install black isort flake8 mypy pytest

      - name: Format code
        run: |
          isort .
          black .

      - name: Commit formatting changes
        if: ${{ github.ref != 'refs/heads/main' }} # only on branches
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "chore: apply formatting fixes (black + isort)"

      - name: Lint
        run: |
          flake8 . || echo "::warning file=./ description=flake8 issues"
          mypy .

      - name: Test
        run: pytest -q